export const ADD_CITY = 'ADD_CITY'
export const REMOVE_CITY = 'REMOVE_CITY'

export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA'
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS'
export const FETCH_WEATHER_DATA_FAILURE = 'FETCH_WEATHER_DATA_FAILURE'

export const REMOVE_WEATHER_DATA = 'REMOVE_WEATHER_DATA'